name: Eksekusi Bombardir Server Cloud
on: [workflow_dispatch]

jobs:
  k6_cloud_test:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode Skrip
        uses: actions/checkout@v4

      - name: Jalankan Grafana k6 Secara Otomatis
        uses: grafana/k6-action@v0.3.1
        with:
          filename: skrip_ekstrim.js
